version: '3'
services:
    web:
        build: .
        ports:
            - "7799:7799"
    mysql:
        image: mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=training
            - MYSQL_DATABASE=spring_training
            - MYSQL_USER=spring
            - MYSQL_PASSWORD=training