## YAML Template.
security:
  oauth2:
    client:
      client-id: springTraining
      client-secret: mostSecretClient
      scope: read,write
      auto-approve-scopes: '.*' 
server:
    port: 7799
spring:
    jpa:
        database: MYSQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                connection:
                    charSet: UTF-8
                hbm2ddl:
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    datasource:
        url: jdbc:mysql://mysql:3306/spring_training?reconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
        username: spring
        password: training
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 5